services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api_network

  backend:
    build:
      dockerfile: ./backend/WebApi/Dockerfile
    container_name: backend
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - api_network

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - api_network

volumes:
  postgres-data:

networks:
  api_network:
    driver: bridge